# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associate',
            options={'verbose_name': 'Associate', 'verbose_name_plural': 'Associates'},
        ),
        migrations.AlterModelOptions(
            name='classified',
            options={'verbose_name': 'Classified', 'verbose_name_plural': 'Classifieds'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='classified',
            name='site',
            field=models.URLField(default=' ', verbose_name='Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associate',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Cell Phone'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='complement',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='rg',
            field=models.CharField(max_length=10, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='classified',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='classified',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='benefit',
            field=models.CharField(max_length=100, verbose_name='Benefit'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
