# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_association_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='association_information',
            name='home_description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
