# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_association_information_home_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('phone1', models.CharField(max_length=11, verbose_name='Phone')),
                ('phone2', models.CharField(max_length=11, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Useful_phone',
                'verbose_name_plural': 'Useful_phones',
            },
        ),
    ]
