# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160529_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Classified')),
                ('classified_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.Classified', verbose_name='Classified')),
            ],
            options={
                'verbose_name': 'Image classified',
                'verbose_name_plural': 'Images classified',
            },
        ),
        migrations.AlterField(
            model_name='imagenews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='imagenews',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.News', verbose_name='News'),
        ),
    ]
