# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 20:46
from __future__ import unicode_literals

from django.db import migrations, models

from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160529_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='associated_from',
            field=models.DateField(default=timezone.now, verbose_name='Associated from'),
            preserve_default=False,
        ),
    ]
