# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_associate_associated_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='associated_from',
        ),
    ]
