# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160530_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category_associates',
            new_name='CategoryAssociates',
        ),
        migrations.RenameModel(
            old_name='Useful_phone',
            new_name='UsefulPhone',
        ),
    ]
