# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160530_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery')),
            ],
            options={
                'verbose_name': 'Image gellery',
                'verbose_name_plural': 'Images galleries',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery'),
        ),
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.URLField(default=datetime.datetime(2016, 6, 5, 5, 18, 35, 987276, tzinfo=utc), verbose_name='Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='gallery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.Gallery', verbose_name='Gallery'),
        ),
    ]
