# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160605_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='associated_from',
            field=models.DateField(default=datetime.datetime(2016, 6, 5, 5, 21, 49, 153582, tzinfo=utc), verbose_name='Associated from'),
            preserve_default=False,
        ),
    ]
