# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_associate_associated_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('document_type', models.CharField(choices=[(None, ''), ('S', 'Statute'), ('R', 'Record'), ('C', 'Craft'), ('D', 'Documents')], max_length=1, verbose_name='Documents')),
                ('document', models.FileField(blank=True, null=True, upload_to='Documents')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'verbose_name': 'Document',
            },
        ),
        migrations.AlterField(
            model_name='association_information',
            name='home_description',
            field=models.TextField(verbose_name='Home Description'),
        ),
        migrations.AlterField(
            model_name='association_information',
            name='long_description',
            field=models.TextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='association_information',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description'),
        ),
    ]
