# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_member_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='charge',
            field=models.CharField(max_length=80, verbose_name='Charge'),
        ),
    ]
