# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160616_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association_information',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='usefulphone',
            name='phone1',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='usefulphone',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
