# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160617_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[(None, ''), ('S', 'Statute'), ('R', 'Record'), ('C', 'Craft'), ('D', 'Documents'), ('H', 'Schedule')], max_length=1, verbose_name='Documents'),
        ),
    ]
