# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160618_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 3, 0, 56, 27, 954091, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery'),
        ),
    ]
