# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160802_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='News'),
        ),
    ]
